on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: 'build image'
        run: docker build -t ${{ secrets.USERNAME }}/mee .

      - name: 'login'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}

      - name: 'push image'
        run: docker push ${{ secrets.USERNAME }}/mee

      
      
      

